# Generated by Django 3.1.3 on 2020-11-21 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('description', models.TextField()),
                ('designer', models.CharField(max_length=75)),
                ('year_released', models.IntegerField(max_length=4)),
                ('total_players', models.IntegerField(max_length=3)),
                ('duration', models.IntegerField()),
                ('age_restriction', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('datestamp', models.DateTimeField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', related_query_name='review', to='raterprojectapi.games')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', related_query_name='review', to='raterprojectapi.players')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', related_query_name='rating', to='raterprojectapi.games')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', related_query_name='rating', to='raterprojectapi.players')),
            ],
        ),
        migrations.AddField(
            model_name='games',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', related_query_name='player', to='raterprojectapi.players'),
        ),
        migrations.CreateModel(
            name='GameImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameimages', related_query_name='gameimage', to='raterprojectapi.games')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameimages', related_query_name='gameimage', to='raterprojectapi.players')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('games', models.ManyToManyField(related_name='game_categories', related_query_name='game_category', to='raterprojectapi.Games')),
            ],
        ),
    ]
