# Generated by Django 3.1.3 on 2020-11-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='age_restriction',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='games',
            name='total_players',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='games',
            name='year_released',
            field=models.IntegerField(),
        ),
    ]
