# Generated by Django 3.1.3 on 2020-12-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0002_auto_20201121_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='games',
        ),
        migrations.AddField(
            model_name='games',
            name='gamecat',
            field=models.ManyToManyField(related_name='game_categories', related_query_name='game_category', to='raterprojectapi.Categories'),
        ),
    ]
